[browser]
gatherUsageStats = false

[server]
headless = true
fileWatcherType = "poll"

[theme]
base = "light"
primaryColor = "#008F70"
backgroundColor = "#EEF5F3"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#193A33"
font = "sans serif"
